version: "3.9"

services:
  webapp:
    image: webapp:1.0
    ports:
      - "8080:8080"

    environment:
      SPRING_APPLICATION_NAME: webapp

      SPRING_CONFIG_IMPORT: "optional:configtree:/run/secrets/"

      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      BOOTSTRAP_ADMIN_LOGIN: "${BOOTSTRAP_ADMIN_LOGIN}"

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SERVER_ERROR_INCLUDE_BINDING_ERRORS: always

    secrets:
      - source: db_password
        target: spring.datasource.password
      - source: bootstrap_admin_password
        target: bootstrap.admin.password

secrets:
  db_password:
    external: true
  bootstrap_admin_password:
    external: true